#!/usr/bin/env ts-node
/**
 * Refresh cookies from Zoom in headless mode
 * 
 * Usage:
 *   npm run refresh-cookies
 * 
 * This script:
 * 1. Loads your existing cookies
 * 2. Opens Zoom.us in headless mode with those cookies
 * 3. Waits for the page to fully load
 * 4. Captures updated/refreshed cookies from the browser
 * 5. Saves them back to .cookies
 */

import { chromium } from 'playwright';
import fs from 'fs';
import path from 'path';

const ZOOM_URL = 'https://zoom.us';
const COOKIES_DIR = path.join(process.cwd(), '.cookies');
const RAW_COOKIES_FILE = path.join(COOKIES_DIR, '.raw_cookies');
const NETSCAPE_COOKIES_FILE = path.join(COOKIES_DIR, 'cookies.txt');

async function main() {
  console.log('🔄 Refreshing Zoom Cookies (Headless Mode)\n');

  // Check if cookies exist
  if (!fs.existsSync(RAW_COOKIES_FILE)) {
    console.error('❌ No cookies found!');
    console.error(`   Run: npm run capture-cookies first`);
    process.exit(1);
  }

  // Load existing cookies
  const rawCookieString = fs.readFileSync(RAW_COOKIES_FILE, 'utf8');
  console.log(`📝 Loaded existing cookies\n`);

  const browser = await chromium.launch({ 
    headless: true,  // Headless mode
    args: ['--disable-blink-features=AutomationControlled']
  });

  try {
    const context = await browser.newContext();
    const page = await context.newPage();

    // Parse existing cookies and add them to the context
    const cookies = parseCookieString(rawCookieString);
    console.log(`🍪 Adding ${cookies.length} cookies to browser context\n`);

    // Set cookies in the browser
    await context.addCookies(cookies);

    console.log('🌐 Opening authenticated meeting dashboard...');
    await page.goto('https://skyscanner.zoom.us/meeting', { waitUntil: 'networkidle', timeout: 60000 });

    console.log('✅ Page loaded. Waiting for JavaScript to settle...');
    await page.waitForTimeout(3000);

    // Capture all cookies from the browser (including any new ones set by JS)
    const updatedCookies = await context.cookies();
    
    if (updatedCookies.length === 0) {
      console.error('❌ No cookies found after loading!');
      process.exit(1);
    }

    console.log(`🍪 Captured ${updatedCookies.length} cookies from browser\n`);

    // Format 1: Raw cookie string
    const newRawCookieString = updatedCookies
      .map(c => `${c.name}=${c.value}`)
      .join('; ');

    fs.writeFileSync(RAW_COOKIES_FILE, newRawCookieString, 'utf8');
    console.log(`📝 Saved raw cookies: ${RAW_COOKIES_FILE}`);

    // Format 2: Netscape format
    const netscapeCookies = formatNetscapeCookies(updatedCookies);
    fs.writeFileSync(NETSCAPE_COOKIES_FILE, netscapeCookies, 'utf8');
    console.log(`📝 Saved Netscape format: ${NETSCAPE_COOKIES_FILE}\n`);

    // Show important cookies
    console.log('🔑 Updated cookies:');
    const importantCookies = ['zoom_us_sid', 'zoom_us_ppid', 'zm_jwt', 'zm_authenticator', '_zm_ssid'];
    for (const name of importantCookies) {
      const cookie = updatedCookies.find(c => c.name === name);
      if (cookie) {
        const value = cookie.value.substring(0, 30) + (cookie.value.length > 30 ? '...' : '');
        console.log(`   ✓ ${cookie.name}: ${value}`);
      }
    }

    console.log('\n✅ Cookies refreshed successfully!');
    process.exit(0);

  } catch (error) {
    console.error('❌ Error:', error);
    process.exit(1);
  } finally {
    await browser.close();
  }
}

/**
 * Parse cookie string (name=value; name=value) into browser-compatible format
 */
function parseCookieString(cookieString: string): any[] {
  return cookieString
    .split(';')
    .map(cookie => cookie.trim())
    .filter(cookie => cookie)
    .map(cookie => {
      const [name, value] = cookie.split('=');
      return {
        name: name.trim(),
        value: value.trim(),
        url: 'https://zoom.us',
      };
    });
}

/**
 * Convert Playwright cookies to Netscape format
 */
function formatNetscapeCookies(cookies: any[]): string {
  const lines = [
    '# Netscape HTTP Cookie File',
    '# This file is generated by zoom-cli refresh-cookies script',
    '# Do not edit manually\n',
  ];

  for (const cookie of cookies) {
    const httponly = cookie.httpOnly ? '#HttpOnly_' : '';
    const domain = cookie.domain.startsWith('.') ? cookie.domain : '.' + cookie.domain;
    const flag = cookie.domain.startsWith('.') ? 'TRUE' : 'FALSE';
    const secure = cookie.secure ? 'TRUE' : 'FALSE';
    const expiry = cookie.expires ? Math.floor(cookie.expires * 1000) : '0';

    lines.push(
      `${httponly}${domain}\t${flag}\t${cookie.path}\t${secure}\t${expiry}\t${cookie.name}\t${cookie.value}`
    );
  }

  return lines.join('\n');
}

main();
