/**
 * Cookie Management Utilities
 * 
 * Handles:
 * - Cookie parsing and serialization
 * - Raw cookie string format (for HTTP headers)
 * - Netscape format (for curl, wget, etc.)
 * - Cookie storage and loading
 */

export interface Cookie {
  name: string;
  value: string;
  domain: string;
  path: string;
  expires?: number;
  httpOnly: boolean;
  secure: boolean;
  sameSite?: string;
}

/**
 * Parse raw cookie string into Cookie objects
 * Format: "name1=value1; name2=value2; ..."
 * 
 * Handles values with equals signs (e.g., JWT tokens with base64 padding)
 */
export function parseRawCookieString(raw: string): Record<string, string> {
  const cookies: Record<string, string> = {};
  
  raw.split(';').forEach(pair => {
    const trimmed = pair.trim();
    if (!trimmed) return;
    
    // Find first '=' to split name from value (value may contain '=')
    const eqIndex = trimmed.indexOf('=');
    if (eqIndex === -1) return;
    
    const name = trimmed.substring(0, eqIndex).trim();
    const value = trimmed.substring(eqIndex + 1).trim();
    
    if (name && value) {
      cookies[name] = value;
    }
  });
  
  return cookies;
}

/**
 * Serialize cookies to raw cookie string (for HTTP headers)
 */
export function serializeToRawCookieString(cookies: Cookie[]): string {
  return cookies
    .map(c => `${c.name}=${c.value}`)
    .join('; ');
}

/**
 * Format cookies to Netscape format
 * Format: domain, flag, path, secure, expiry, name, value
 * 
 * Netscape format is compatible with curl, wget, and other tools
 */
export function formatNetscapeCookies(cookies: Cookie[]): string {
  const lines = [
    '# Netscape HTTP Cookie File',
    '# This file is generated by zoom-cli',
    '# Do not edit manually\n',
  ];

  for (const cookie of cookies) {
    const httponly = cookie.httpOnly ? '#HttpOnly_' : '';
    const domain = cookie.domain.startsWith('.') ? cookie.domain : '.' + cookie.domain;
    const flag = cookie.domain.startsWith('.') ? 'TRUE' : 'FALSE';
    const secure = cookie.secure ? 'TRUE' : 'FALSE';
    const expiry = cookie.expires ? Math.floor(cookie.expires * 1000) : '0';

    lines.push(
      `${httponly}${domain}\t${flag}\t${cookie.path}\t${secure}\t${expiry}\t${cookie.name}\t${cookie.value}`
    );
  }

  return lines.join('\n');
}

/**
 * Parse Netscape format cookies
 */
export function parseNetscapeCookies(content: string): Cookie[] {
  const cookies: Cookie[] = [];
  
  const lines = content.split('\n');
  for (const line of lines) {
    const trimmed = line.trim();
    
    // Skip empty lines and pure comment lines (not #HttpOnly_ prefixed)
    if (!trimmed || (trimmed.startsWith('#') && !trimmed.startsWith('#HttpOnly_'))) {
      continue;
    }

    const parts = line.split('\t');
    if (parts.length < 7) continue;

    let domain = parts[0].trim();
    const httpOnly = domain.startsWith('#HttpOnly_');
    if (httpOnly) {
      domain = domain.replace('#HttpOnly_', '');
    }

    const path = parts[2].trim();
    const secure = parts[3].trim() === 'TRUE';
    const expiry = parseInt(parts[4].trim(), 10);
    const name = parts[5].trim();
    const value = parts[6].trim();

    cookies.push({
      name,
      value,
      domain,
      path,
      expires: expiry > 0 ? expiry / 1000 : undefined,
      httpOnly,
      secure,
    });
  }

  return cookies;
}

/**
 * Extract Cookie header from a cookie string
 * This is what you pass to HTTP requests
 */
export function getCookieHeader(cookies: Record<string, string>): string {
  return Object.entries(cookies)
    .map(([name, value]) => `${name}=${value}`)
    .join('; ');
}

/**
 * Check if cookies look valid (basic validation)
 */
export function validateCookies(cookies: Record<string, string>): {
  valid: boolean;
  warnings: string[];
} {
  const warnings: string[] = [];

  if (Object.keys(cookies).length === 0) {
    warnings.push('No cookies found');
  }

  // Check for common Zoom cookies
  const commonZoomCookies = ['zoom_us_sid', 'zoom_us_ppid', 'zm_jwt'];
  const foundZoomCookies = commonZoomCookies.filter(name => cookies[name]);
  
  if (foundZoomCookies.length === 0) {
    warnings.push('No Zoom-specific cookies found');
  }

  return {
    valid: warnings.length === 0,
    warnings,
  };
}

/**
 * Merge multiple cookie sets, newer values override older
 */
export function mergeCookies(
  base: Record<string, string>,
  updates: Record<string, string>
): Record<string, string> {
  return { ...base, ...updates };
}
